apiVersion: "integreatly.org/v1alpha1"
kind: "WebApp"
metadata:
  name: "tutorial-web-app-operator"
  labels:
    app: "tutorial-web-app"
spec:
  app_label: "tutorial-web-app"
  template:
    path: "/home/tutorial-web-app-operator/deploy/template/tutorial-web-app.yml"
    parameters:
      WEBAPP_IMAGE: "quay.io/integreatly/tutorial-web-app"
      WEBAPP_IMAGE_TAG: "latest"
      OPENSHIFT_OAUTHCLIENT_ID: "tutorial-web-app"
      OPENSHIFT_HOST: ""
      SSO_ROUTE: ""
      WALKTHROUGH_LOCATIONS: "https://github.com/integr8ly/tutorial-web-app-walkthroughs.git"